# Generated by Django 5.1.4 on 2024-12-13 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='robot',
            options={'ordering': ('serial',), 'verbose_name': 'Робот', 'verbose_name_plural': 'Роботы'},
        ),
        migrations.AlterField(
            model_name='robot',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='robot',
            index=models.Index(fields=['serial'], name='robots_robo_serial_0ec49a_idx'),
        ),
    ]
