# Generated by Django 5.1.4 on 2024-12-17 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0002_alter_robot_options_alter_robot_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='robot',
            name='status',
            field=models.CharField(choices=[('booked', 'Забронирован'), ('available', 'Доступен')], default='available', max_length=10),
        ),
    ]
