# Generated by Django 5.1.4 on 2024-12-17 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customer_options_alter_customer_email'),
        ('orders', '0002_alter_order_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-status', 'created_at'), 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2022-12-31 23:59:59'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('waiting', 'Ожидание'), ('booked', 'Забронирован')], default='waiting', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='customers.customer'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-status', 'created_at'], name='orders_orde_status_5634b6_idx'),
        ),
    ]
