# Generated by Django 5.1.4 on 2024-12-18 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customer_options_alter_customer_email'),
        ('orders', '0004_alter_order_unique_together'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='orders_orde_status_5634b6_idx',
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='orders_orde_status_25e057_idx'),
        ),
    ]
